import type { Metadata } from "next";
import { Besley, Abril_Fatface } from "next/font/google";
import "./globals.css";

const besley = Besley({
  subsets: ["latin"],
  variable: "--besley",
  weight: ["400", "700"],
  style: ["normal", "italic"]
});
const abrilFatface = Abril_Fatface({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--Abril_Fatface"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${besley.variable} ${abrilFatface.variable}`}>
      <body
        className={`${abrilFatface.className} flex h-auto items-center justify-center bg-[#DADCE7]`}
      >
        {children}
      </body>
    </html>
  );
}
